#!/bin/sh

bin_path="/usr/local"
ProcName="btserver"

while true
do
sleep 30
stillRunning=$(ps -ef | grep -w $ProcName | grep -v grep)
if [ ! "$stillRunning" ];then
	$bin_path/bin/$ProcName /$bin_path/etc/beetalk.conf &
fi
done
